version: 2
jobs:
  UI test:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: yarn
      - run: yarn test

  UI compile:
    docker:
      - image: circleci/node:9
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: yarn
      - run: yarn compile
      - persist_to_workspace:
          root: .
          paths: dist

  Server lint:
    docker:
      - image: circleci/python:3.4
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: lint
          command: |
            . venv/bin/activate
            find ./tntfl -name \*.py -exec pycodestyle --ignore=E501 {} +
            find . -name \*.cgi -exec pycodestyle --ignore=E501 {} +
  Server test:
    docker:
      - image: circleci/python:3.4
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python run_tests.py
  Server coverage:
    docker:
      - image: circleci/python:3.4
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: coverage
          command: |
            . venv/bin/activate
            coverage run --source=tntfl --omit=tntfl/test/* run_tests.py
            codeclimate-test-reporter

workflows:
  version: 2
  build:
    jobs:
      - UI test
      - UI compile
      - Server lint
      - Server test:
          requires:
            - UI compile
      - Server coverage:
          requires:
            - Server test
